# Asn1_verbosity, choice in: none, info, annoying
Asn1_verbosity = "none";

ORUs = (
{
  tx_bw = [106];
  rx_bw = [106];
  carrier_tx = [4049760];
  carrier_rx = [4049760];
  prach_config_index = 157;
  prach_msg1_start = 0;
  tdd_period = 5;
  num_dl_slots = 3;
  num_dl_symbols = 6;
  num_ul_slots = 1;
  num_ul_symbols = 4;
  numerology = 1;
  tp_cores = [-1, -1, -1, -1, -1, -1]
});

RUs = (
{
  local_rf       = "no";
  nb_tx          = 1;
  nb_rx          = 1;
  att_tx         = 0;
  att_rx         = 0;
  bands          = [77];
  max_pdschReferenceSignalPower = -27;
  max_rxgain                    = 75;
  sf_extension                  = 0;
  eNB_instances  = [0];
  sl_ahead       = 5;
  tr_preference  = "raw_if4p5"; # important: activate FHI7.2
  do_precoding   = 0; # needs to match O-RU configuration
});


log_config :
{
  global_log_level = "info";
  hw_log_level     = "info";
  phy_log_level    = "info";
  mac_log_level    = "info";
  rlc_log_level    = "info";
  pdcp_log_level   = "info";
  rrc_log_level    = "info";
  ngap_log_level   = "info";
  f1ap_log_level   = "info";
};

fhi_72 = {
  dpdk_devices = ("0000:05:02.0", "0000:05:02.1"); # one VF can be used as well
  dpdk_iova_mode = "VA";
  system_core = 17;
  io_core = 18;
  worker_cores = (19);
  du_addr = ("00:11:22:33:64:68", "00:11:22:33:64:69");
  mtu = 9600;
  app_id = "RU";
  file_prefix = "ru";
  fh_config = ({
    Ta3_up = (200, 470);
    T2a_up = (350, 1200);
    ru_config = {
      iq_width = 16;
      iq_width_prach = 16;
    };
  });
};
